-- AlterTable
ALTER TABLE `notification` MODIFY `type` ENUM('TEAM_INVITE', 'EVENT_REMINDER', 'GENERAL', 'ANNOUNCEMENT', 'RESULT_DECLARATION', 'INVITE_ACCEPTED', 'INVITE_REJECTED', 'EVENT_CANCELLED', 'POSITION_UPDATE', 'QUALIFICATION_UPDATE') NOT NULL;

-- AlterTable
ALTER TABLE `notificationqueue` MODIFY `type` ENUM('TEAM_INVITE', 'EVENT_REMINDER', 'GENERAL', 'ANNOUNCEMENT', 'RESULT_DECLARATION', 'INVITE_ACCEPTED', 'INVITE_REJECTED', 'EVENT_CANCELLED', 'POSITION_UPDATE', 'QUALIFICATION_UPDATE') NOT NULL DEFAULT 'GENERAL';
