-- CreateTable
CREATE TABLE `Event` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(191) NOT NULL,
    `eventName` ENUM('TECH_ROADIES', 'NON_TECH_ROADIES', 'DEBUG', 'QUIZMANIA', 'CODE_RELAY', 'PANCHAYAT', 'SPELL_BEE', 'ROBO_RACE', 'ROBO_WAR', 'TRESURE_HUNT', 'GULLEY_CRICKET', 'DUNK_THE_BALL', 'DART', 'PING_PONG', 'FOOTSOL', 'SOLO_DANCE', 'DUO_DANCE', 'GROUP_DANCE', 'SOLO_SINGING', 'DUO_SINGING', 'GROUP_SINGING', 'SKIT') NOT NULL,
    `eventType` ENUM('TECHNICAL', 'NON_TECHNICAL', 'CULTURAL', 'SPORTS') NOT NULL,
    `participationType` ENUM('SOLO', 'DUO', 'TRIO', 'QUAD', 'QUINTET', 'GROUP') NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `EventParticipant` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `eventId` INTEGER NOT NULL,
    `userId` INTEGER NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `EventParticipant` ADD CONSTRAINT `EventParticipant_eventId_fkey` FOREIGN KEY (`eventId`) REFERENCES `Event`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `EventParticipant` ADD CONSTRAINT `EventParticipant_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `User`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
